services:
  Chaos\CoreModule\System\Entity\LookupEntity:
    class:  Chaos\CoreModule\System\Entity\LookupEntity
    lazy:   true
    shared: false
  Chaos\CoreModule\System\Event\LookupListener:
    class:  Chaos\CoreModule\System\Event\LookupListener
    lazy:   true
    shared: false
  Chaos\CoreModule\System\Service\LookupService:
    class:  Chaos\CoreModule\System\Service\LookupService
    lazy:   true
  LookupEntity: '@Chaos\CoreModule\System\Entity\LookupEntity'
  LookupService: '@Chaos\CoreModule\System\Service\LookupService'
