services:
  Chaos\Core\Account\Entity\UserEntity:
    class:  Chaos\Core\Account\Entity\UserEntity
    lazy:   true
    shared: false
  Chaos\Core\Account\Event\UserListener:
    class:  Chaos\Core\Account\Event\UserListener
    lazy:   true
    shared: false
  Chaos\Core\Account\Service\UserService:
    class:  Chaos\Core\Account\Service\UserService
    lazy:   true
  UserEntity: '@Chaos\Core\Account\Entity\UserEntity'
  UserService: '@Chaos\Core\Account\Service\UserService'
