services:
  Chaos\Module\User\Entity\UserEntity:
    class:  Chaos\Module\User\Entity\UserEntity
    lazy:   true
    shared: false
  Chaos\Module\User\Event\UserListener:
    class:  Chaos\Module\User\Event\UserListener
    lazy:   true
    shared: false
  Chaos\Module\User\Service\UserService:
    class:  Chaos\Module\User\Service\UserService
    lazy:   true
  UserEntity: '@Chaos\Module\User\Entity\UserEntity'
  UserService: '@Chaos\Module\User\Service\UserService'
