services:
  Chaos\Component\Role\RoleEntity:
    class:  Chaos\Component\Role\RoleEntity
    lazy:   true
    shared: false
  Chaos\Component\Role\RoleListener:
    class:  Chaos\Component\Role\RoleListener
    lazy:   true
    shared: false
  Chaos\Component\Role\RoleService:
    class:  Chaos\Component\Role\RoleService
    lazy:   true
  Role: '@Chaos\Component\Role\RoleEntity'
  RoleService: '@Chaos\Component\Role\RoleService'
