services:
  Chaos\Component\User\UserEntity:
    class:  Chaos\Component\User\UserEntity
    lazy:   true
    shared: false
  Chaos\Component\User\UserListener:
    class:  Chaos\Component\User\UserListener
    lazy:   true
    shared: false
  Chaos\Component\User\UserService:
    class:  Chaos\Component\User\UserService
    lazy:   true
  User: '@Chaos\Component\User\UserEntity'
  UserService: '@Chaos\Component\User\UserService'
