services:
  Chaos\CoreModule\Account\Entity\UserEntity:
    class:  Chaos\CoreModule\Account\Entity\UserEntity
    lazy:   true
    shared: false
  Chaos\CoreModule\Account\Event\UserListener:
    class:  Chaos\CoreModule\Account\Event\UserListener
    lazy:   true
    shared: false
  Chaos\CoreModule\Account\Service\UserService:
    class:  Chaos\CoreModule\Account\Service\UserService
    lazy:   true
  UserEntity: '@Chaos\CoreModule\Account\Entity\UserEntity'
  UserService: '@Chaos\CoreModule\Account\Service\UserService'

  Chaos\CoreModule\Account\Entity\RoleEntity:
    class:  Chaos\CoreModule\Account\Entity\RoleEntity
    lazy:   true
    shared: false
  Chaos\CoreModule\Account\Event\RoleListener:
    class:  Chaos\CoreModule\Account\Event\RoleListener
    lazy:   true
    shared: false
  Chaos\CoreModule\Account\Service\RoleService:
    class:  Chaos\CoreModule\Account\Service\RoleService
    lazy:   true
  RoleEntity: '@Chaos\CoreModule\Account\Entity\RoleEntity'
  RoleService: '@Chaos\CoreModule\Account\Service\RoleService'

  Chaos\CoreModule\Account\Entity\PermissionEntity:
    class:  Chaos\CoreModule\Account\Entity\PermissionEntity
    lazy:   true
    shared: false
  Chaos\CoreModule\Account\Event\PermissionListener:
    class:  Chaos\CoreModule\Account\Event\PermissionListener
    lazy:   true
    shared: false
  Chaos\CoreModule\Account\Service\PermissionService:
    class:  Chaos\CoreModule\Account\Service\PermissionService
    lazy:   true
  PermissionEntity: '@Chaos\CoreModule\Account\Entity\PermissionEntity'
  PermissionService: '@Chaos\CoreModule\Account\Service\PermissionService'
