services:
  Chaos\Module\Account\UserEntity:
    class:  Chaos\Module\Account\UserEntity
    lazy:   true
    shared: false
  Chaos\Module\Account\UserListener:
    class:  Chaos\Module\Account\UserListener
    lazy:   true
    shared: false
  Chaos\Module\Account\UserService:
    class:  Chaos\Module\Account\UserService
    lazy:   true
  User: '@Chaos\Module\Account\UserEntity'
  UserService: '@Chaos\Module\Account\UserService'

  Chaos\Module\Account\RoleEntity:
    class:  Chaos\Module\Account\RoleEntity
    lazy:   true
    shared: false
  Chaos\Module\Account\RoleListener:
    class:  Chaos\Module\Account\RoleListener
    lazy:   true
    shared: false
  Chaos\Module\Account\RoleService:
    class:  Chaos\Module\Account\RoleService
    lazy:   true
  Role: '@Chaos\Module\Account\RoleEntity'
  RoleService: '@Chaos\Module\Account\RoleService'

  Chaos\Module\Account\PermissionEntity:
    class:  Chaos\Module\Account\PermissionEntity
    lazy:   true
    shared: false
  Chaos\Module\Account\PermissionListener:
    class:  Chaos\Module\Account\PermissionListener
    lazy:   true
    shared: false
  Chaos\Module\Account\PermissionService:
    class:  Chaos\Module\Account\PermissionService
    lazy:   true
  Permission: '@Chaos\Module\Account\PermissionEntity'
  PermissionService: '@Chaos\Module\Account\PermissionService'
