services:
  Chaos\FeatureModule\Foo\Entity\FooEntity:
    class:  Chaos\FeatureModule\Foo\Entity\FooEntity
    lazy:   true
    shared: false
  Chaos\FeatureModule\Foo\Event\FooListener:
    class:  Chaos\FeatureModule\Foo\Event\FooListener
    lazy:   true
    shared: false
  Chaos\FeatureModule\Foo\Service\FooService:
    class:  Chaos\FeatureModule\Foo\Service\FooService
    lazy:   true
  FooEntity: '@Chaos\FeatureModule\Foo\Entity\FooEntity'
  FooService: '@Chaos\FeatureModule\Foo\Service\FooService'
