app:
  key: '%^APP_KEY%'
  fallback_locale: '%APP_FALLBACK_LOCALE%'
  locale: '%APP_LOCALE%'
  url: '%^APP_URL%'

session:
  cookie: '%SESSION_COOKIE%'
  lifetime: '%^SESSION_LIFETIME%'
  path: '%SESSION_PATH%'
  domain: '%SESSION_DOMAIN%'

#multitenant:
#  enabled: false
#  keymap: ApplicationKey

#dir:
#  api: '%APP_DIR%/public/api'
#  config: '%APP_DIR%/packages/modules/config/custom.yml'
#  uploads: '%APP_DIR%/public/uploads'

#url:
#  api: '%^APP_URL%/api'
#  reset: '%^APP_URL%/#/reset?k='

imports:
  - { resource: writable.yml }
  - { resource: doctrine.yml }
  - { resource: jms.yml }
