app:
  default_route: setting.index
  fallback_locale: en
  locale: en
  theme: element
  url: ''

framework:
  application_key: '%APP_KEY%'

dir:
  api: '%APP_DIR%/public/api'
  config: '%APP_DIR%/packages/modules/config/custom.yml'
  uploads: '%APP_DIR%/public/uploads'

url:
  api: '%APP_URL%/api'
  reset: '%APP_URL%/#/reset?k='

imports:
  - { resource: doctrine.yml }
  - { resource: jms.yml }
  - { resource: custom.yml }
