services:
  Chaos\CoreModule\Account\Entity\RoleEntity:
    class:  Chaos\CoreModule\Account\Entity\RoleEntity
    lazy:   true
    shared: false
  Chaos\CoreModule\Account\Event\RoleListener:
    class:  Chaos\CoreModule\Account\Event\RoleListener
    lazy:   true
    shared: false
  Chaos\CoreModule\Account\Service\RoleService:
    class:  Chaos\CoreModule\Account\Service\RoleService
    lazy:   true
  RoleEntity: '@Chaos\CoreModule\Account\Entity\RoleEntity'
  RoleService: '@Chaos\CoreModule\Account\Service\RoleService'
