services:
  Chaos\Module\Role\Entity\RoleEntity:
    class:  Chaos\Module\Role\Entity\RoleEntity
    lazy:   true
    shared: false
  Chaos\Module\Role\Event\RoleListener:
    class:  Chaos\Module\Role\Event\RoleListener
    lazy:   true
    shared: false
  Chaos\Module\Role\Service\RoleService:
    class:  Chaos\Module\Role\Service\RoleService
    lazy:   true
  RoleEntity: '@Chaos\Module\Role\Entity\RoleEntity'
  RoleService: '@Chaos\Module\Role\Service\RoleService'
