services:
  Chaos\CoreModule\Account\Entity\PermissionEntity:
    class:  Chaos\CoreModule\Account\Entity\PermissionEntity
    lazy:   true
    shared: false
  Chaos\CoreModule\Account\Event\PermissionListener:
    class:  Chaos\CoreModule\Account\Event\PermissionListener
    lazy:   true
    shared: false
  Chaos\CoreModule\Account\Service\PermissionService:
    class:  Chaos\CoreModule\Account\Service\PermissionService
    lazy:   true
  PermissionEntity: '@Chaos\CoreModule\Account\Entity\PermissionEntity'
  PermissionService: '@Chaos\CoreModule\Account\Service\PermissionService'
