services:
  Chaos\Module\Permission\Entity\PermissionEntity:
    class:  Chaos\Module\Permission\Entity\PermissionEntity
    lazy:   true
    shared: false
  Chaos\Module\Permission\Event\PermissionListener:
    class:  Chaos\Module\Permission\Event\PermissionListener
    lazy:   true
    shared: false
  Chaos\Module\Permission\Service\PermissionService:
    class:  Chaos\Module\Permission\Service\PermissionService
    lazy:   true
  PermissionEntity: '@Chaos\Module\Permission\Entity\PermissionEntity'
  PermissionService: '@Chaos\Module\Permission\Service\PermissionService'
