services:
  Chaos\Module\System\LookupEntity:
    class:  Chaos\Module\System\LookupEntity
    lazy:   true
    shared: false
  Chaos\Module\System\LookupListener:
    class:  Chaos\Module\System\LookupListener
    lazy:   true
    shared: false
  Chaos\Module\System\LookupService:
    class:  Chaos\Module\System\LookupService
    lazy:   true
  Lookup: '@Chaos\Module\System\LookupEntity'
  LookupService: '@Chaos\Module\System\LookupService'
