services:
  Chaos\Component\Lookup\LookupEntity:
    class:  Chaos\Component\Lookup\LookupEntity
    lazy:   true
    shared: false
  Chaos\Component\Lookup\LookupListener:
    class:  Chaos\Component\Lookup\LookupListener
    lazy:   true
    shared: false
  Chaos\Component\Lookup\LookupService:
    class:  Chaos\Component\Lookup\LookupService
    lazy:   true
  Lookup: '@Chaos\Component\Lookup\LookupEntity'
  LookupService: '@Chaos\Component\Lookup\LookupService'
